import { Sparkles } from "lucide-react";

import RecommendationCard from "./cards/RecommendationCard";

function AIRecommendationSection() {
  const demoRecommendations = [
    {
      tmdbId: 157336,
      title: "Interstellar",
      mediaType: "movie",
      genre: "Science Fiction",
      confidence: 0.94,
      reason:
        "You frequently enjoy emotional science-fiction movies with deep storytelling and strong character development.",
    },
    {
      tmdbId: 155,
      title: "The Dark Knight",
      mediaType: "movie",
      genre: "Action • Crime",
      confidence: 0.91,
      reason:
        "Based on your ratings and reviews, superhero movies with darker themes align well with your preferences.",
    },
  ];

  return (
    <section>
      <div className="mb-8 flex items-center gap-3">
        <Sparkles
          size={28}
          className="text-red-500"
        />

        <div>
          <h2 className="text-3xl font-bold text-white">
            AI Recommendations
          </h2>

          <p className="mt-2 text-zinc-400">
            Personalized suggestions generated by your local AI recommendation engine.
          </p>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {demoRecommendations.map((movie) => (
          <RecommendationCard
            key={movie.tmdbId}
            recommendation={movie}
          />
        ))}
      </div>
    </section>
  );
}

export default AIRecommendationSection;